name: Create Trello card on opened issues

on:
  issues:
    types: [opened]

jobs:
  create_trello_card_job:
    runs-on: ubuntu-latest
    name: Create Trello Card
    steps:
      - name: Call trello-github-actions
        uses: Yleisradio/github-action-trello-integration@v1.1.0
        with:
          action: issue_opened_create_card
        env:
          GITHUB_TOKEN: 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
          TRELLO_API_KEY: 8afa7d73d7e2ffd927bafb04bb0be456
          TRELLO_API_TOKEN: ATTA3e27b0285ae29424ef3e5ac53a43c4337df62f4ddb0b983f3ca7b5a07eae378b1AF91611
          # TRELLO_BOARD_ID must match a board. GH repo should connect
          # to exactly one board, but Trello board may connect to multiple
          # GH repositories.
          TRELLO_BOARD_ID: 695d236016daa147d1caf470
          # Backlog list ID
          TRELLO_LIST_ID: 69836fe2552f57b5aca2a5df
